server:
  port: 888
eureka:
  client:
    service-url:
      defaultZone: http://Admin:sunlight@localhost:5000/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
  boot:
    admin:
      client:
        username: mario
        password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'
